#Ausführen nach Deploy um eine neu Calibredb erzeugen:
#https://github.com/linuxserver/docker-calibre-web/issues/30
#https://hub.docker.com/r/linuxserver/calibre-web
#docker exec -it CONTAINER_ID /bin/bash -c "cd /app/calibre/bin && calibredb restore_database --really-do-it --with-library /books"
#docker exec -it calibre-web chmod a+w /books

---
version: "2.1"
services:
  calibre-web:
    image: linuxserver/calibre-web:latest
    container_name: calibre-web
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - DOCKER_MODS=linuxserver/mods:universal-calibre #optional
    volumes:
      - config:/config
      - library:/books
    ports:
      - 8083:8083
    restart: unless-stopped
volumes:
  config:
  library:


