#https://hub.docker.com/r/cturra/ntp
version: '3.9'

services:
  ntp:
    build: .
    image: cturra/ntp:latest
    container_name: ntp
    restart: always
    ports:
      - 123:123/udp
    environment:
      - NTP_SERVERS=de.pool.ntp.org
      - LOG_LEVEL=0
      - TZ=Europe/Berlin
      - NOCLIENTLOG=true
