---
- hosts: localhost
  gather_facts: no
  vars_files: ./vars.yml
  tasks:
   - name: Clone a virtual machine from Windows template and customize
     community.vmware.vmware_guest:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      datacenter:  "{{ datacenter }}"
      datastore: "{{ datastore }}"
      cluster: "{{ cluster }}"
      validate_certs: no
      state: powered-on
      folder: "{{ folder }}"
      name: "{{ item }}"
      template: "{{ template }}"
      networks:
       - name: "{{ network }}"
         ip: "{{ ip }}"
         netmask: "{{ netmask }}"
         gateway: "{{ gateway }}"
         dns_servers:
          - "{{ dns_servers }}"
         type: static
        #domain: my_domain
      #customization:
       # domain: "{{ dnsname }}"
       # password: "{{ domainpw }}"
       # runonce:
        #  - powershell.exe C:\PSScripts\installwinrm.ps1 
     with_items: "{{ windowsserver }}"
 
