---
# DB User anlegen funktioniert nicht muss separat gemacht werden
- hosts: "{{ srchost }}"
  remote_user: root
  #strategy: mitogen_linear
  vars_files: 
   - ./vars/vars.yml  
  tasks:
  - name: Copy .my.cnf for mysql operations
    copy:
      src: .my.cnf
      dest: /root
      owner: root
      group: root
      mode: 0600
 
  - name: Dump DB from Vhost
    shell: |
       "mysqldump {{ db }} > {{ db }}.sql"     
  - name: "Copy DBDump to Ansible Host"
    fetch:
       src: "/root/{{ db }}.sql"
       dest: /tmp/
       flat: yes
   



- hosts: "{{ desthost }}"
  remote_user: root
  #strategy: mitogen_linear
  vars_files:
   - ./vars/vars.yml
  tasks:
  - name: Copy .my.cnf for mysql operations
    copy:
      src: .my.cnf
      dest: /root
      owner: root
      group: root
      mode: 0600
 
  - name: Create a new database for vhost
    shell: |
        "mysql -e Create Database {{ db }}"
 # - name: Create database user with password and privilege him to db
  #  community.mysql.mysql_user:
   #   state: present
    #  name: "{{ db_user }}" 
    #  password: "{{ db_pw }}"
    #  priv:
     #   '{{ db }}.*': 'ALL'
  
  - name: "Copy DBDump to Target Host"
    copy:
       src: "/tmp/{{ db }}.sql"
       dest: /root
       owner: root
       group: root
       mode: 0644
      # remote_src: yes
 
  - name: Import database from vhost to Target Host
    shell: | 
        "mysql {{ db }} > {{ db }}.sql"
   
      
