---
- hosts: webserver
  remote_user: root
  tasks:
   - name: Delete CheckMkScript
     shell: |
        rm /usr/lib/check_mk_agent/local/testservice 
     register: cmd

   - debug:
       msg: "{{ cmd.stdout }}"
     

   - name: Discover new Changes and Activate changes only from cmkautouser
     delegate_to: 127.0.0.1                                                      
     shell: |
        bash /home/rne/ansible-checkmk/disandactchanges 
     register: cmd

   - debug:
       msg: "{{ cmd.stdout }}"


