#!/bin/bash



for host in $(grep -E 'cms0|web0' inventorymegabit.yml | tail -n 20 | cut -d ' ' -f1);
do
     curl "https://$HOST_NAME/$SITE_NAME/check_mk/webapi.py?action=discover_services&_username=$USERNAME&_secret=$PASSWORD" -d 'request={"hostname":"'"$host"'","mode":"fixall"}' | jq
    # curl "https://$HOST_NAME/$SITE_NAME/check_mk/webapi.py?_secret=$PASSWORD&_username=$USERNAME&action=activate_changes" -d 'request={"sites":["master"],"allow_foreign_changes":"0"}' | jq

done

  curl "https://$HOST_NAME/$SITE_NAME/check_mk/webapi.py?_secret=$PASSWORD&_username=$USERNAME&action=activate_changes" -d 'request={"sites":["master"],"allow_foreign_changes":"0"}' | jq

