# Docker Compose file for Grafana, Telegraf, and Alertmanager
services:
  # Telegraf Service
  telegraf:
    image: telegraf:latest
    container_name: telegraf
    restart: always
    user: "1001:1001"
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - HOSTNAME=${HOSTNAME}
    networks:
      - monitoring
        #security_opt:
        #- no-new-privileges:true
        #read_only: true

  # Grafana Service
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    user: "1001:1001"
    volumes:
      -  ./grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=
      - GF_SECURITY_ADMIN_PASSWORD=
    ports:
      - "3002:3000"
    networks:
      - monitoring
        #security_opt:
        #- no-new-privileges:true
        #read_only: true

  # Alertmanager Service
  alertmanager:
    image: prom/alertmanager:latest
    container_name: alertmanager
    restart: always
    user: "1001:1001"
    volumes:
      - ./alertmanager:/etc/alertmanager
      - ./alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml:ro
    ports:
      - "9093:9093"
    networks:
      - monitoring
        #security_opt:
        # - no-new-privileges:true
        #read_only: true
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    restart: always
    user: "1000:1000"
    volumes:
      - ./influxdb:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=telegraf
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=
    ports:
      - "8086:8086"
    networks:
      - monitoring
        #security_opt:
        #- no-new-privileges:true
        #read_only: true
networks:
  monitoring:
    external: true
    driver: bridge
