version: "3.5"

services:
  grafana8:
    image: grafana/grafana:latest
    container_name: grafana8
    volumes:
      - grafana-data:/var/lib/grafana
    user: 0:0
    environment:
     - GF_SECURITY_ADMIN_PASSWORD=“admin”
     - GF_SECURITY_ADMIN_USER=“admin”
    ports:
      - "3010:3000"
    restart: always
volumes:
    grafana-data:

