---
- hosts: windows
  vars_files:
    - vars.yml
  tasks:
   - name: Install Features 
     ansible.windows.win_feature:
       name:
       - AD-Certificate
       - ADCS-Cert-Authority
       state: present
       include_management_tools: yes
       include_sub_features: no
     register: ils
  
  
  

 
