---
- hosts: windows
  vars_files:
    - vars.yml
  tasks:
    - name: Install Active Directory 
      ansible.windows.win_feature:
       name:
       - AD-Domain-Services
       - RSAT-ADDS
       - RSAT-AD-AdminCenter
       - RSAT-ADDS-Tools
       state: present
       include_management_tools: yes
       include_sub_features: yes
      register: ad_install
   
    - name: Reboot if installing Active Directory feature requires it
      ansible.windows.win_reboot:
      when: ad_install.reboot_required
  
