---
- hosts: veeam
  gather_facts: no
  vars_files: 
  - vars.yml
  tasks:
   - name: Join domain
     ansible.windows.win_domain_membership:
       dns_domain_name: "{{ dnsname }}"
       hostname: "{{ hostname }}"
       domain_admin_user: "{{ domainuser }}"
       domain_admin_password: "{{ domainpw }}"
       #ou: "{{ ldappath }}"
       state: domain
     register: domain_state
   - debug: var=domain_state

   - name: Reboot after joining
     ansible.windows.win_reboot:
     when: domain_state.reboot_required
