---
- hosts: exchange
  gather_facts: no
  vars: 
   - ./vars.yml
  tasks:
   - name: Join domain
   ansible.windows.win_domain_membership:
      dns_domain_name: "{{ dnsname }}"
      hostname: "{{ clienthostname }}"
      domain_admin_user: "{{ domainuser }}"
      domain_admin_password: "{{ domainpw }}"
      domain_ou_path: "{{ ldappath }}"
      state: domain
    register: domain_state

  - name: Reboot after joining
    ansible.windows.win_reboot:
    when: domain_state.reboot_required
