#https://hub.docker.com/_/odoo
version: '3.1'
services:
  web:
    image: odoo:17.0
    user: odoo
    depends_on:
      - db
    ports:
      - "8069:8069"
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=admin1234
      - DB_PORT=5432
    volumes:
      - odoo-web-data:/var/lib/odoo
      - odoo-addons:/mnt/extra-addons
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
    #security_opt:
     # - no-new-privileges:true
    #cap_drop:
     # - ALL

  db:
    image: postgres:15
    user: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=admin1234
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
    #security_opt:
     # - no-new-privileges:true
    #cap_drop:
     # - ALL

volumes:
  odoo-web-data:
  odoo-db-data:
  odoo-addons: