version: "3.7"
services:
  db:
    image: postgres
    container_name: local_pgdb
    restart: always
    ports:
      - "54320:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: admin123
    volumes:
      - /local_pgdata:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: kallassani@megabit.net
      PGADMIN_DEFAULT_PASSWORD: admin123
    volumes:
      - /pgadmin-data:/var/lib/pgadmin

volumes:
  local_pgdata:
  pgadmin-data:
