---
- hosts: localhost
  vars_files: ./vars.yml
  gather_facts: no
  tasks: 
   - name: Set the state of the virtual machines to poweron
     community.vmware.vmware_guest_powerstate:
       hostname: "{{ vcenter_hostname }}"
       username: "{{ vcenter_username }}"
       password: "{{ vcenter_password }}"
       folder: "{{ folder }}"
       validate_certs: no
       name: "{{ item }}"
       state: powered-on
     register: deploy
     with_items: "{{ windowsserver }}"

      
