---
- hosts: veeam
  tasks:
    - name: Rename Host
      ansible.windows.win_hostname:
        name: ansveeam
      register: res
    
    - name: Reboot
      ansible.windows.win_reboot:
      when: res.reboot_required
