#https://docs.rundeck.com/docs/administration/install/linux-deb.html#installing-rundeck
version: '3'
services:
  rundeck:
    image: rundeck/rundeck:4.17.0
    restart: unless-stopped
    links:
      - mysql
    depends_on:
      - mysql
    environment:
      RUNDECK_DATABASE_DRIVER: org.mariadb.jdbc.Driver
      RUNDECK_DATABASE_USERNAME: rundeck
      RUNDECK_DATABASE_PASSWORD: rundeck
      RUNDECK_DATABASE_URL: jdbc:mysql://mysql/rundeck?autoReconnect=true&useSSL=false
      RUNDECK_STORAGE_CONVERTER_1_CONFIG_PASSWORD: rundeck
      RUNDECK_CONFIG_STORAGE_CONVERTER_1_CONFIG_PASSWORD: rundeck
      RUNDECK_GRAILS_URL: http://192.168.0.30:4440
      RUNDECK_SERVER_FORWARDED: 'true'
    ports:
      - '4440:4440'
  mysql:
    image: mysql:5.7
    restart: unless-stopped
    expose:
      - '3306'
    environment:
      - MYSQL_ROOT_PASSWORD=rundeck
      - MYSQL_DATABASE=rundeck
      - MYSQL_USER=rundeck
      - MYSQL_PASSWORD=rundeck
    volumes:
       - dbdata:/var/lib/mysql

volumes:
    dbdata:
