#!/bin/bash

  output=/tmp/output-checkmk.txt
  echo -n "0 \"AnzahlderZugriffeaufVHostsProMinute\" " > $output
  anzahl=0
  for vhost in $( ls -1 /var/www | grep "\." ); do
    #echo $i
    hf=/tmp/vhost$vhost  # alte anzahl get requests
    AAL=/var/www/$vhost/logs/access.log
    z=$(cat $AAL | grep -c GET)
    difftime=$(( $(date +%s) - $(stat -c %Y $hf) ))
    if [ $difftime -lt 600 ];
    then
        h=`cat $hf`
        diff=$(( $z - $h )) # neu hinzugekommenen get requests
    fi

    echo $z > $hf

    if [[ $anzahl -gt 0 ]]; then echo -n "|" >> $output; fi
    echo -n "$vhost=$diff" >> $output
    anzahl=1
  done
  echo " Anzahl der Zugriffe auf Vhosts" >> $output
  echo "" >> $output
  cat $output
