---
- hosts: localhost
  vars_files: ./vars.yml
  tasks: 
   - name: Set the state of the virtual machines to restart
     community.vmware.vmware_guest_powerstate:
       hostname: "{{ vcenter_hostname }}"
       username: "{{ vcenter_username }}"
       password: "{{ vcenter_password }}"
       folder: "{{ folder }}"
       validate_certs: no
       name: "{{ item }}"
       state: restarted
     register: deploy
     with_items: "{{ linuxserver }}"
   
