---
- hosts: "{{ srchost }}"
  remote_user: root
  #strategy: mitogen_linear
  vars_files:
   - ./vars/vars.yml
  tasks:
  - name: zip Vhost
    delegate_to: "{{ srchost }}"
    archive:
     path:
        - "{{ vhostdir }}/stats"
        - "{{ vhostdir }}/logs"
        - "{{ vhostdir }}/htdocs"
        - "{{ vhostdir }}/conf"
     dest: "{{ archivedir }}/{{ vhost }}.zip"
     format: zip


    
  - name: "Copy Vhost zip to Ansible Host"
    fetch:
       src: "{{ archivedir }}/{{ vhost }}.zip"
       dest: "/tmp/{{ vhost }}.zip"
       flat: yes


- hosts: "{{ desthost }}"
  remote_user: root
  #strategy: mitogen_linear
  vars_files:
   - ./vars/vars.yml
  tasks:
   # - name: Call a2addsite if the vhost doesnt exist on target host
    #  shell:
    #    a2addsite.sh {{ vhostdir }} user

  - name: "Copy Zip to Target Host" 
    copy: 
        src: "/tmp/{{ vhost }}.zip"
        dest: "{{ archivedir }}"
        owner: root
        group: root
        mode: 0644
        #remote_src: yes

 
  - name: Extract Vhost on Target Host
    unarchive:      
       src: "{{ archivedir }}/{{ vhost }}.zip"       
       dest: "{{ vhostdir }}"
       remote_src: yes
   
      
