#!/bin/bash
kubectl apply -n portainer -f https://raw.githubusercontent.com/portainer/k8s/master/deploy/manifests/portainer/portainer-lb.yaml
sleep 3
PortainerIP=$(k3s kubectl describe pods -n portainer | grep Node: | awk -F '  +' '{print $2}')
Hostname=$(hostname)
IPMaster=$(hostname -I | cut -d' ' -f1)
echo "Portainer deployed on K3s Cluster with Controller Host $Hostname/$IPMaster and running on Port 9000 and 9443"
curl -L https://downloads.portainer.io/agent-stack-ce211.yml -o agent-stack.yml && docker stack deploy --compose-file=agent-stack.yml portainer-agent
echo "Portainer Agents are deployed for retrieving all Informations about the Docker Swarm Cluster. Please Add in Enviroments under Portainer a Site to see your Docker Nodes and Containers on the Hosts $Hostname/$IPMaster"
