#!/bin/bash
kubectl apply -n portainer -f https://raw.githubusercontent.com/portainer/k8s/master/deploy/manifests/portainer/portainer.yaml
sleep 3
PortainerIP=$(k3s kubectl describe pods -n portainer | grep Node: | awk -F '  +' '{print $2}')
Hostname=$(hostname)
IPMaster=$(hostname -I | cut -d' ' -f1)
echo "Portainer deployed on K3s Cluster with Controller Host $Hostname/$IPMaster and running on Host $PortainerIP"
