#https://hasura.io/docs/latest/getting-started/docker-simple/
#https://hub.docker.com/r/hasura/graphql-engine
version: '3.6'
services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: hasuradb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin1234
    volumes:
    - db_data:/var/lib/postgresql/data
  graphql-engine:
    image: hasura/graphql-engine:latest
    ports:
    - "8080:8080"
    depends_on:
    - "postgres"
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://admin:admin1234@postgres:5432/hasuradb
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      ## uncomment next line to set an admin secret
      # HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey
volumes:
  db_data:
