#https://hub.docker.com/r/bitnami/neo4j/
version: '2'

networks:
  neo4j-network:
    driver: bridge

services:
  neo4j:
    image: bitnami/neo4j:latest
    networks:
      - neo4j-network
    ports:
      - '7474:7474'
      - '7473:7473'
      - '7687:7687'
    environment:
      - NEO4J_PASSWORD=admin1234#
      - NEO4J_ALLOW_UPGRADE=true
      - NEO4J_BIND_ADDRESS=172.20.0.2
      - NEO4J_BOLT_PORT_NUMBER=7687
    volumes:
       - neo4jvol:/neo4jdata
volumes:
  neo4jvol:
