version: "3.7"

services:

  php:
    image: php:8.0-fpm
    volumes:
        - phpconfig:/var/www/phpmyadmin
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:latest
    restart: always
    volumes:
      - mariadb-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin123

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 8005:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mariadb
    depends_on:
      - mariadb

volumes:
  mariadb-data:
  phpconfig:
