#!/bin/bash
sudo apt install fail2ban -y
sudo cp /etc/fail2ban/jail.{conf,local}
cat << EOF > /etc/fail2ban/jail.local
[DEFAULT]
 bantime = 24h
 ignoreip = 127.0.0.1/8 xxx.xxx.xxx.xxx
 ignoreself = true

 [sshd]
 enabled = true
 port = 22
 filter = sshd
 logpath = /var/log/auth.log
 maxretry = 3
 bantime = 99999h

[dovecot]

enabled         = true
port            = pop3,pop3s,imap,imaps,submission,465,sieve
logpath         = /var/log/mail.log
filter          = dovecot
maxretry        = 3
findtime        = 1200
bantime         = 21600
action          = iptables-allports


[postfix]

enabled         = true
mode            = more
port            = smtp,465,submission
logpath         = /var/log/mail.log
filter          = postfix
maxretry        = 3
findtime        = 1200
bantime         = 21600
action          = iptables-allports

[webexploits]
enabled   = false
logpath = /var/log/apache*/*error.log
filter = webexploits
port    = http,https
bantime = 1440m
findtime = 1440m
maxretry = 0


# detect password authentication failures
[apache]
enabled  = true
port     = http,https
filter   = apache-auth
logpath  = /var/log/apache*/*error.log
maxretry = 6

# detect potential search for exploits and php vulnerabilities
[apache-noscript]
enabled  = true
port     = http,https
filter   = apache-noscript
logpath  = /var/log/apache*/*error.log
maxretry = 6

# detect Apache overflow attempts
[apache-overflows]
enabled  = true
port     = http,https
filter   = apache-overflows
logpath  = /var/log/apache*/*error.log
maxretry = 2

# detect failures to find a home directory on a server
[apache-nohome]
enabled  = true
port     = http,https
filter   = apache-nohome
logpath  = /var/log/apache*/*error.log
maxretry = 2



EOF






systemctl restart fail2ban

systemctl status fail2ban
fail2ban-client status

echo "Finished. Fail2ban installed with Apache2"
