#https://ghostfol.io/en/start
# Edit the .env
version: '3.9'
services:
  ghostfolio:
    image: ghostfolio/ghostfolio:latest
    environment:
      - DATABASE_URL=postgresql://ghost:dRDGH4nQ3ZcakmXywmer@postgres:5432/ghostfolio-db?connect_timeout=300&sslmode=prefer
      - NODE_ENV=production
      - REDIS_HOST='redis'
      - REDIS_PASSWORD=dRDGH4nQ3ZcakmXywmer
    ports:
      - 3333:3333
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:12
    environment:
      - POSTGRES_DB=ghostfolio-db
      - POSTGRES_USER=ghost
      - POSTGRES_PASSWORD=dRDGH4nQ3ZcakmXywmer
    volumes:
      - postgres:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    environment:
      - REDIS_PORT=6379
      - REDIS_PASSWORD=dRDGH4nQ3ZcakmXywmer
volumes:
  postgres:
